# Generated by Django 5.1.4 on 2025-01-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('arts', 'Arts and Culture'), ('education', 'Education and Workshops'), ('sports', 'Sports and Fitness'), ('social', 'Social and Networking'), ('food', 'Food and Drink'), ('entertainment', 'Entertainment'), ('technology', 'Technology and Innovation'), ('family', 'Family and Kids'), ('religious', 'Religious and Spiritual'), ('holidays', 'Holidays and Seasonal'), ('business', 'Business and Corporate'), ('health', 'Health and Wellness'), ('niche', 'Other Niche Events')], default='arts', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default=None, upload_to='event-images/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
