# Generated by Django 5.1.4 on 2025-02-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_category_event_image_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('sold_out', 'Sold Out')], default='active', max_length=50),
        ),
    ]
