# Generated by Django 5.1.4 on 2025-02-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tickets_available',
            field=models.IntegerField(default=0),
        ),
    ]
