# Generated by Django 5.1.5 on 2025-02-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_event_tickets_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Canceled", "Canceled"),
                    ("Sold Out", "Sold Out"),
                ],
                default="active",
                max_length=50,
            ),
        ),
    ]
