# Generated by Django 5.1.4 on 2025-02-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='purchased_at',
            new_name='purchased_on',
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('sold_out', 'Sold Out')], default='active', max_length=50),
        ),
    ]
