# Generated by Django 5.1.4 on 2025-02-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_rename_purchased_at_ticket_purchased_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('sold_out', 'Sold Out'), ('past', 'Compeleted')], default='active', max_length=50),
        ),
    ]
