# Generated by Django 5.1.4 on 2025-09-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_alter_event_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
